dialogs_moc = qt6.preprocess(
    moc_headers: files(
        'AboutDialog.h',
        'AccountDialog.h',
        'AddRemoteDialog.h',
        'AmendDialog.h',
        'BranchDelegate.h',
        'BranchTableModel.h',
        'CheckoutDialog.h',
        'CloneDialog.h',
        'CommitDialog.h',
        'ConfigDialog.h',
        'DeleteBranchDialog.h',
        'DeleteTagDialog.h',
        'DiffPanel.h',
        'ExternalToolsDialog.h',
        'ExternalToolsModel.h',
        'MergeDialog.h',
        'NewBranchDialog.h',
        'PluginsPanel.h',
        'PullRequestDialog.h',
        'RebaseConflictDialog.h',
        'RemoteDialog.h',
        'RemoteTableModel.h',
        'RenameBranchDialog.h',
        'SettingsDialog.h',
        'StartDialog.h',
        'SubmoduleDelegate.h',
        'SubmoduleTableModel.h',
        'TagDialog.h',
        'ThemeDialog.h',
        'UpdateSubmodulesDialog.h',
    ),
    moc_sources: files(
        'AmendDialog.cpp',
        'CloneDialog.cpp',
        'ConfigDialog.cpp',
        'SettingsDialog.cpp',
        'StartDialog.cpp',
        'ThemeDialog.cpp',
    ),
    # Feed OS defines into moc since meson doesn't set that up for us
    moc_extra_arguments: is_win ? ['-D_WIN32'] : ['-DQ_OS_UNIX'],
    dependencies: [qt6_dep, pawmmit_common],
)

dialogs_src = [
    'AboutDialog.cpp',
    'AccountDialog.cpp',
    'AddRemoteDialog.cpp',
    'AmendDialog.cpp',
    'BranchDelegate.cpp',
    'BranchTableModel.cpp',
    'CheckoutDialog.cpp',
    'CloneDialog.cpp',
    'CommitDialog.cpp',
    'ConfigDialog.cpp',
    'DeleteBranchDialog.cpp',
    'DeleteTagDialog.cpp',
    'DiffFileDialog.cpp',
    'DiffPanel.cpp',
    'ExternalToolsDialog.cpp',
    'ExternalToolsModel.cpp',
    'HotkeysPanel.cpp',
    'IconLabel.cpp',
    'MergeDialog.cpp',
    'NewBranchDialog.cpp',
    'PluginsPanel.cpp',
    'PullRequestDialog.cpp',
    'RebaseConflictDialog.cpp',
    'RemoteDialog.cpp',
    'RemoteTableModel.cpp',
    'RenameBranchDialog.cpp',
    'SettingsDialog.cpp',
    'StartDialog.cpp',
    'SubmoduleDelegate.cpp',
    'SubmoduleTableModel.cpp',
    'TagDialog.cpp',
    'ThemeDialog.cpp',
    'UpdateSubmodulesDialog.cpp',
]

dialogs_lib = static_library(
    'dialogs',
    dialogs_src + dialogs_moc,
    dependencies: [
        pawmmit_common,
        version_dep,
        translation_dep,
        cli_dep,
        conf_dep,
        cred_dep,
        host_dep,
        index_dep,
    ])

dialogs_dep = declare_dependency(
    link_with: dialogs_lib,
    include_directories: include_directories('.'),
)
